services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobcrafts_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobcrafts_frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173
