# Generated by Django 5.2.12 on 2026-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cover_letter_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
