# Generated by Django 5.2.12 on 2026-03-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0002_usersubscription_cover_letter_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='interview_prep_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
