# Generated by Django 5.2.12 on 2026-03-04 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0003_usersubscription_interview_prep_uses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=180)),
                ('gap_reason', models.CharField(max_length=180)),
                ('gap_start', models.CharField(max_length=80)),
                ('gap_end', models.CharField(max_length=80)),
                ('what_you_did', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_gap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
