# Generated by Django 5.2.12 on 2026-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0006_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='ats_bonus_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
