# Generated by Django 5.2.12 on 2026-03-06 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0009_emailcampaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='expiry_reminder_sent_for_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
