# Generated by Django 5.2.12 on 2026-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0012_linkedinoptimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cover_letter_bonus_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='interview_prep_bonus_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='resume_bonus_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
