# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0012_linkedinoptimization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='experience',
            field=models.JSONField(default=list, help_text='[{job_role, achievements: [str]}]'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.JSONField(default=list, help_text='[{description, link}]'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.JSONField(default=list, help_text='[str]'),
        ),
    ]
