# Generated by Django 5.2.12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeai', '0013_add_bonus_credits_for_carryover'),
        ('resumeai', '0013_alter_portfolio_experience_alter_portfolio_projects_and_more'),
    ]

    operations = [
    ]
